# Generated by Django 3.0.2 on 2020-07-06 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=100)),
                ('temp1', models.CharField(max_length=100)),
                ('press', models.CharField(max_length=100)),
                ('humi', models.CharField(max_length=100)),
                ('sdesc', models.CharField(max_length=100)),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
